version: '3'

services:
  app:
    container_name: application
    build: ./app
    depends_on:
      - database
    ports:
      - "5000:5000"
    volumes:
      - ./app:/application
  
  database:
    container_name: database
    image: mysql:5.7
    environment: 
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: teste
    volumes:
      - data-volume:/var/lib/mysql

volumes:
  data-volume: